### PR TITLE
Update engine.h

### PR DESCRIPTION
**Pull request by benganellison**
fix for https://github.com/dotse/bbk/issues/4

### CODE REVIEW

**Comment by initgoran** [comment]
Please make sure the fix works on all platforms, including Windows.
Cf. https://github.com/initgoran/bbk/commit/95002e2fb308e597de26beca47633595cd8b787c

**Comment by benganellison** [comment]
What do you mean? Did this break something?

**Comment by benganellison** [comment]
> Please make sure the fix works on all platforms, including Windows.
> Cf. [initgoran@95002e2](https://github.com/initgoran/bbk/commit/95002e2fb308e597de26beca47633595cd8b787c)

Why don't you create a pull requests based on your repo?

**Comment by initgoran** [comment]
> Why don't you create a pull requests based on your repo?

Well, mostly because I haven't yet tested my changes on Windows :)

**Pull request closed without merging**
